#!/bin/sh

set -eu

if [ "${MUSIKCUBE_INTERACTIVE:-0}" -eq 1 ]; then
	caddy --agree --conf "${HOME}/.caddy/Caddyfile" &
	musikcube
else
	caddy --agree --conf "${HOME}/.caddy/Caddyfile" & CADDY_PID=$!
	musikcube >/dev/null & MUSIKCUBE_PID=$!
	while sleep 30; do
		if [ ! -e "/proc/${CADDY_PID}" ]; then
			printf -- '%s\n' 'Caddy is not running, exiting...'
			exit 1
		elif [ ! -e "/proc/${MUSIKCUBE_PID}" ]; then
			printf -- '%s\n' 'Musikcube is not running, exiting...'
			exit 1
		fi
	done
fi
